const path = require('path');
const { query } = require('../config/db');
const { uploadBuffer, removeFile, createSignedUrl, publicUrl, BUCKET_CV, BUCKET_LOGOS } = require('../config/storage');
const { v4: uuidv4 } = require('uuid');
const { mapUser } = require('./authController');

const getProfile=async(req,res,next)=>{try{const r=await query('SELECT * FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount)return res.status(404).json({success:false,message:'Usuario no encontrado'});const user=mapUser(r.rows[0]);if(user.logo)user.logo=publicUrl(BUCKET_LOGOS,r.rows[0].logo);res.json({success:true,user});}catch(e){next(e);}};
const updateProfile=async(req,res,next)=>{try{const isCompany=req.user.role==='empresa';const fields=isCompany?['name','phone','companyName','sector','description','website']:['name','phone','skills','experience','education'];const sets=[];const vals=[];for(const f of fields){if(req.body[f]!==undefined){const dbField={companyName:'company_name'}[f]||f;let v=req.body[f];if(f==='skills')v=JSON.stringify(Array.isArray(v)?v:String(v).split(',').map(x=>x.trim()).filter(Boolean));vals.push(v);sets.push(`${dbField}=$${vals.length}`);}}if(!sets.length)return res.status(400).json({success:false,message:'No hay cambios'});vals.push(new Date(),req.user.id);const r=await query(`UPDATE users SET ${sets.join(',')},updated_at=$${vals.length-1} WHERE id=$${vals.length} RETURNING *`,vals);const user=mapUser(r.rows[0]);if(user.logo)user.logo=publicUrl(BUCKET_LOGOS,r.rows[0].logo);res.json({success:true,message:'Perfil actualizado',user});}catch(e){next(e);}};
const uploadCV=async(req,res,next)=>{try{if(!req.file)return res.status(400).json({success:false,message:'Archivo CV requerido'});const old=await query('SELECT cv FROM users WHERE id=$1',[req.user.id]);if(!old.rowCount)return res.status(404).json({success:false,message:'Usuario no encontrado'});const ext=path.extname(req.file.originalname).toLowerCase();const filePath=`${req.user.id}/${uuidv4()}${ext}`;await uploadBuffer(BUCKET_CV,filePath,req.file.buffer,req.file.mimetype);await query('UPDATE users SET cv=$1,updated_at=NOW() WHERE id=$2',[filePath,req.user.id]);if(old.rows[0].cv)await removeFile(BUCKET_CV,old.rows[0].cv);res.json({success:true,message:'CV subido correctamente',cv:filePath});}catch(e){next(e);}};
const uploadLogo=async(req,res,next)=>{try{if(!req.file)return res.status(400).json({success:false,message:'Imagen requerida'});const old=await query('SELECT logo FROM users WHERE id=$1',[req.user.id]);if(!old.rowCount)return res.status(404).json({success:false,message:'Usuario no encontrado'});const ext=path.extname(req.file.originalname).toLowerCase();const filePath=`${req.user.id}/${uuidv4()}${ext}`;await uploadBuffer(BUCKET_LOGOS,filePath,req.file.buffer,req.file.mimetype);await query('UPDATE users SET logo=$1,updated_at=NOW() WHERE id=$2',[filePath,req.user.id]);if(old.rows[0].logo)await removeFile(BUCKET_LOGOS,old.rows[0].logo);res.json({success:true,message:'Logo actualizado',logo:publicUrl(BUCKET_LOGOS,filePath)});}catch(e){next(e);}};
const getCompanies=async(req,res,next)=>{try{const q=req.query.q;const params=[];let where=`role='empresa'`;if(q){params.push(`%${q}%`);where+=` AND (company_name ILIKE $1 OR sector ILIKE $1)`;}const r=await query(`SELECT * FROM users WHERE ${where} ORDER BY company_name`,params);res.json({success:true,companies:r.rows.map(x=>{const u=mapUser(x);u.logo=x.logo?publicUrl(BUCKET_LOGOS,x.logo):null;return u;})});}catch(e){next(e);}};
const getOwnCvUrl=async(req,res,next)=>{try{const r=await query('SELECT cv FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount||!r.rows[0].cv)return res.status(404).json({success:false,message:'No hay CV'});res.json({success:true,url:await createSignedUrl(BUCKET_CV,r.rows[0].cv,300)});}catch(e){next(e);}};

module.exports={getProfile,updateProfile,uploadCV,uploadLogo,getCompanies,getOwnCvUrl};
